version: '3.3'
services:
  ffmpeg:
    image: praul/ffmpeg
    container_name: ffmpeg
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Europe/Berlin
    volumes:
      - './app/:/app' #you can mount your own /app/convert.sh to change / adjust ffmpeg settings
      - './convert:/convert' # mount a folder to /convert. Place your files in convert/source. They will be transcoded to convert/output and the source file will be moved to convert/done
    group_add:
      - 44
      - 100
  
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
